
import wx
'''
ID_ABORT
ID_ABOUT
ID_ADD
ID_ANY
ID_APPLY
ID_AUTO_HIGHEST
ID_AUTO_LOWEST
ID_BACKWARD
ID_BOLD
ID_BOTTOM
ID_CANCEL
ID_CDROM
ID_CLEAR
ID_CLOSE
ID_CLOSE_ALL
ID_CLOSE_FRAME
ID_CONTEXT_HELP
ID_CONVERT
ID_COPY
ID_CUT
ID_DEFAULT
ID_DELETE
ID_DOWN
ID_DUPLICATE
ID_EDIT
ID_EXECUTE
ID_EXIT
ID_FILE
ID_FILE1
ID_FILE2
ID_FILE3
ID_FILE4
ID_FILE5
ID_FILE6
ID_FILE7
ID_FILE8
ID_FILE9
ID_FILECTRL
ID_FILEDLGG
ID_FIND
ID_FIRST
ID_FLOPPY
ID_FORWARD
ID_HARDDISK
ID_HELP
ID_HELP_COMMANDS
ID_HELP_CONTENTS
ID_HELP_CONTEXT
ID_HELP_INDEX
ID_HELP_PROCEDURES
ID_HELP_SEARCH
ID_HIGHEST
ID_HOME
ID_ICONIZE_FRAME
ID_IGNORE
ID_INDENT
ID_INDEX
ID_INFO
ID_ITALIC
ID_JUMP_TO
ID_JUSTIFY_CENTER
ID_JUSTIFY_FILL
ID_JUSTIFY_LEFT
ID_JUSTIFY_RIGHT
ID_LAST
ID_LOWEST
ID_MAXIMIZE_FRAME
ID_MDI_WINDOW_ARRANGE_ICONS
ID_MDI_WINDOW_CASCADE
ID_MDI_WINDOW_FIRST
ID_MDI_WINDOW_LAST
ID_MDI_WINDOW_NEXT
ID_MDI_WINDOW_PREV
ID_MDI_WINDOW_TILE_HORZ
ID_MDI_WINDOW_TILE_VERT
ID_MORE
ID_MOVE_FRAME
ID_NETWORK
ID_NEW
ID_NO
ID_NONE
ID_NOTOALL
ID_OK
ID_OPEN
ID_PAGE_SETUP
ID_PASTE
ID_PREFERENCES
ID_PREVIEW
ID_PREVIEW_CLOSE
ID_PREVIEW_FIRST
ID_PREVIEW_GOTO
ID_PREVIEW_LAST
ID_PREVIEW_NEXT
ID_PREVIEW_PREVIOUS
ID_PREVIEW_PRINT
ID_PREVIEW_ZOOM
ID_PREVIEW_ZOOM_IN
ID_PREVIEW_ZOOM_OUT
ID_PRINT
ID_PRINT_SETUP
ID_PROPERTIES
ID_REDO
ID_REFRESH
ID_REMOVE
ID_REPLACE
ID_REPLACE_ALL
ID_RESET
ID_RESIZE_FRAME
ID_RESTORE_FRAME
ID_RETRY
ID_REVERT
ID_REVERT_TO_SAVED
ID_SAVE
ID_SAVEAS
ID_SELECTALL
ID_SELECT_COLOR
ID_SELECT_FONT
ID_SEPARATOR
ID_SETUP
ID_SORT_ASCENDING
ID_SORT_DESCENDING
ID_SPELL_CHECK
ID_STATIC
ID_STOP
ID_STRIKETHROUGH
ID_SYSTEM_MENU
ID_TOP
ID_UNDELETE
ID_UNDERLINE
ID_UNDO
ID_UNINDENT
ID_UP
ID_VIEW_DETAILS
ID_VIEW_LARGEICONS
ID_VIEW_LIST
ID_VIEW_SMALLICONS
ID_VIEW_SORTDATE
ID_VIEW_SORTNAME
ID_VIEW_SORTSIZE
ID_VIEW_SORTTYPE
ID_YES
ID_YESTOALL
ID_ZOOM_100
ID_ZOOM_FIT
ID_ZOOM_IN
ID_ZOOM_OUT
'''

'''
打印出来wxpython所有的ID_开头的button
'''
for x in dir(wx):
    if x.startswith('ID_'):
        print (x)

class MyPanel(wx.Panel):
    def __init__(self, parent):
        super(MyPanel, self).__init__(parent)
        # Make some buttons
        sizer = wx.BoxSizer(wx.HORIZONTAL)
        for bid in (wx.ID_OK, wx.ID_CANCEL,wx.ID_APPLY, wx.ID_HELP,wx.ID_UP):
            button = wx.Button(self, bid)
            sizer.Add(button, 0, wx.ALL, 5)
        self.SetSizer(sizer)

class MyFrame(wx.Frame):
    def __init__(self, parent, id=wx.ID_ANY, title="",pos=wx.DefaultPosition, size=wx.DefaultSize,
                style=wx.DEFAULT_FRAME_STYLE,name="MyFrame"):
        super(MyFrame, self).__init__(parent, id, title,pos, size, style, name)
        self.panel = MyPanel(self)


if __name__ == "__main__":
    app = wx.App()
    frame = MyFrame(parent=None)
    frame.Show()
    app.MainLoop()